---
#setup ngrok client
- name: copy ngrok executable (x86)
  copy:
    src: "files/ngrok"
    dest: "{{ngrok_exec_path}}"
    owner: "{{ngrok_user | d('root')}}"
    mode: 744
  when: ansible_architecture == "x86_64"
  register: ngrok__register_cli_app_override
- name: copy ngrok executable  (arm)
  copy:
    src: "{{ngrok_arm_local_exec_path}}"
    dest: "{{ngrok_exec_path}}"
    owner: "{{ngrok_user | d('root')}}"
    mode: 744
  when: ansible_architecture == "armv7l"
  register: ngrok__register_cli_app_override

- name: create ngrok config dir if not exists
  file: path="{{ngrok_config_dir}}" state=directory
  become: true

- name: copy ngrok config template
  template:
    src: etc/ngrok/config.yml.j2
    dest: "{{ngrok_config_dir}}/config.yml"
- name: copy service template
  template:
    src: etc/systemd/system/ngrok.service.j2
    dest: /etc/systemd/system/ngrok.service
    owner: "root"
    group: "root"
    mode: "0644"
  become: true
  register: ngrok__register_cli_custom_override

- name: Reload systemd daemon
  systemd:
    daemon_reload: true
  when: ngrok__register_cli_custom_override is changed
        or ngrok__force_reload | d()
- name: start ngrok service
  service:
    name: ngrok
    state: reloaded
  when: ngrok__register_cli_custom_override is changed
        or ngrok__register_cli_app_override is changed

- name: setup client ufw firewall
  import_tasks: firewall.yml
  become: true
#  when: net__ufw | d (false)
